name: Backend CI

on:
  pull_request:
    branches:
      - master
      - develop
      - release/*
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------
      # Read Java version from Gradle
      # -----------------------------
      - name: Read Java version from Gradle
        id: java_version
        run: |
          JAVA_VERSION=$(grep -oP 'JavaLanguageVersion.of\(\K[0-9]+' questevent-backend/build.gradle || true)
          if [ -z "$JAVA_VERSION" ]; then
            echo "Java version not found in build.gradle"
            exit 1
          fi
          echo "java=$JAVA_VERSION" >> $GITHUB_OUTPUT
      # -----------------------------
      # Setup Java
      # -----------------------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.java_version.outputs.java }}
          cache: gradle

      # -----------------------------
      # Grant permission for Gradle wrapper
      # -----------------------------
      - name: Make Gradle wrapper executable
        run: chmod +x questevent-backend/gradlew

      # -----------------------------
      # Build & Test
      # -----------------------------
      - name: Build and test with Gradle
        working-directory: questevent-backend
        run: ./gradlew clean build jacocoTestReport

      # -----------------------------
      # Upload JaCoCo HTML report
      # -----------------------------
      - name: Upload test coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-coverage
          path: questevent-backend/build/reports/jacoco/test/html

      # -----------------------------
      # Publish JaCoCo to GitHub Pages
      # -----------------------------
      - name: Publish JaCoCo report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: questevent-backend/build/reports/jacoco/test/html
          destination_dir: jacoco
          disable_nojekyll: true

      # -----------------------------
      # Comment coverage on PR
      # -----------------------------
      - name: Comment JaCoCo coverage on PR
        if: >
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: questevent-backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}